### ISSUE TITLE
Core crash on escort quest Tomb of the Lightbringer id 9446

### ISSUE THREAD

**Issue by Mr-Deadbeat** [trickerer/Trinity-Bots#45]
OS Ubuntu 20.04 server
TC Commit c2a0b78a051ea3301d8769b2c11fae00e14fe095

Trinity-bots Commit 24a2cbc028b1f3f6a4cf84360ad98b8680fb1483

the crash occurs when Anchorite Truuen reaches the destination at uthers tomb the core crashes instantly

Crash log below

```Thread 7 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff999ff700 (LWP 10346)]
0x0000555555bc6afa in Player::GetTeam (this=0x0) at /home/gameadm/source/trinity/src/server/game/Entities/Player/Player.h:1759
1759	        uint32 GetTeam() const { return m_team; }
(gdb) info threads
  Id   Target Id                                       Frame 
  1    Thread 0x7ffff4de3fc0 (LWP 10336) "worldserver" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555558594560 <MapManager::instance()::instance+448>)
    at ../sysdeps/nptl/futex-internal.h:183
  2    Thread 0x7ffff43ff700 (LWP 10340) "worldserver" 0x00007ffff6f915ce in epoll_wait (epfd=6, events=0x7ffff43fcdc0, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  3    Thread 0x7ffff3bfe700 (LWP 10341) "worldserver" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffff4865198) at ../sysdeps/nptl/futex-internal.h:183
  4    Thread 0x7ffff33fd700 (LWP 10342) "worldserver" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffff48623a4) at ../sysdeps/nptl/futex-internal.h:183
  5    Thread 0x7ffff2bfc700 (LWP 10344) "worldserver" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffff48622e0) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7ffff23fb700 (LWP 10345) "worldserver" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffff4862224) at ../sysdeps/nptl/futex-internal.h:183
* 7    Thread 0x7fff999ff700 (LWP 10346) "worldserver" 0x0000555555bc6afa in Player::GetTeam (this=0x0) at /home/gameadm/source/trinity/src/server/game/Entities/Player/Player.h:1759
  8    Thread 0x7fff851fe700 (LWP 10347) "worldserver" 0x00007ffff6f915ce in epoll_wait (epfd=23, events=0x7fff851fbd20, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
(gdb)

(gdb) bt
#0  0x0000555555bc6afa in Player::GetTeam (this=0x0) at /home/gameadm/source/trinity/src/server/game/Entities/Player/Player.h:1759
#1  0x00005555564c7847 in Condition::Meets (this=0x7fffbbee6f80, sourceInfo=...) at /home/gameadm/source/trinity/src/server/game/Conditions/ConditionMgr.cpp:214
#2  0x00005555564ca115 in ConditionMgr::IsObjectMeetToConditionList (this=0x55555858e160 <ConditionMgr::instance()::instance>, sourceInfo=..., conditions=std::vector of length 1, capacity 1 = {...})
    at /home/gameadm/source/trinity/src/server/game/Conditions/ConditionMgr.cpp:915
#3  0x00005555564ca776 in ConditionMgr::IsObjectMeetToConditions (this=0x55555858e160 <ConditionMgr::instance()::instance>, sourceInfo=..., conditions=std::vector of length 1, capacity 1 = {...})
    at /home/gameadm/source/trinity/src/server/game/Conditions/ConditionMgr.cpp:945
#4  0x00005555564cba76 in ConditionMgr::IsObjectMeetingSmartEventConditions (this=0x55555858e160 <ConditionMgr::instance()::instance>, entryOrGuid=17233, eventId=0, sourceType=0, unit=0x7fff83164000, 
    baseObject=0x7fff82381000) at /home/gameadm/source/trinity/src/server/game/Conditions/ConditionMgr.cpp:1063
#5  0x00005555562b91f4 in SmartScript::ProcessEventsFor (this=0x7fff81bb89a8, e=SMART_EVENT_JUST_SUMMONED, unit=0x7fff83164000, var0=0, var1=0, bvar=false, spell=0x0, gob=0x0)
    at /home/gameadm/source/trinity/src/server/game/AI/SmartScripts/SmartScript.cpp:239
#6  0x00005555562b3f1d in SmartAI::IsSummonedBy (this=0x7fff81bb8980, summoner=0x7fff83164000) at /home/gameadm/source/trinity/src/server/game/AI/SmartScripts/SmartAI.cpp:649
#7  0x00005555565ef2b6 in TempSummon::InitSummon (this=0x7fff82381000) at /home/gameadm/source/trinity/src/server/game/Entities/Creature/TemporarySummon.cpp:245
#8  0x0000555556634a64 in Map::SummonCreature (this=0x7fffc2d71400, entry=17233, pos=..., properties=0x0, duration=60000, summoner=0x7fff83164000, spellId=0, vehId=0)
    at /home/gameadm/source/trinity/src/server/game/Entities/Object/Object.cpp:1956
#9  0x0000555556634e91 in WorldObject::SummonCreature (this=0x7fff83164000, entry=17233, pos=..., despawnType=TEMPSUMMON_TIMED_DESPAWN, despawnTime=..., spellId=0)
    at /home/gameadm/source/trinity/src/server/game/Entities/Object/Object.cpp:2014
#10 0x0000555556634ff6 in WorldObject::SummonCreature (this=0x7fff83164000, id=17233, x=971.859985, y=-1825.42004, z=84, o=0.293500006, despawnType=TEMPSUMMON_TIMED_DESPAWN, despawnTime=...)
    at /home/gameadm/source/trinity/src/server/game/Entities/Object/Object.cpp:2030
#11 0x00005555562c1f04 in SmartScript::ProcessAction (this=0x7fff83173528, e=..., unit=0x0, var0=0, var1=0, bvar=false, spell=0x0, gob=0x0)
    at /home/gameadm/source/trinity/src/server/game/AI/SmartScripts/SmartScript.cpp:1273
#12 0x00005555562d6a7a in SmartScript::ProcessEvent (this=0x7fff83173528, e=..., unit=0x0, var0=17, var1=17238, bvar=false, spell=0x0, gob=0x0)
    at /home/gameadm/source/trinity/src/server/game/AI/SmartScripts/SmartScript.cpp:3237
#13 0x00005555562b9238 in SmartScript::ProcessEventsFor (this=0x7fff83173528, e=SMART_EVENT_WAYPOINT_REACHED, unit=0x0, var0=17, var1=17238, bvar=false, spell=0x0, gob=0x0)
    at /home/gameadm/source/trinity/src/server/game/AI/SmartScripts/SmartScript.cpp:240
#14 0x00005555562b2d6d in SmartAI::WaypointReached (this=0x7fff83173500, nodeId=17, pathId=17238) at /home/gameadm/source/trinity/src/server/game/AI/SmartScripts/SmartAI.cpp:369
#15 0x0000555556bf2636 in WaypointMovementGenerator<Creature>::OnArrived (this=0x7fff83cd7680, owner=0x7fff83164000)
    at /home/gameadm/source/trinity/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp:261
#16 0x0000555556bf2124 in WaypointMovementGenerator<Creature>::DoUpdate (this=0x7fff83cd7680, owner=0x7fff83164000, diff=100)
    at /home/gameadm/source/trinity/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp:202
#17 0x0000555556bf3cd3 in MovementGeneratorMedium<Creature, WaypointMovementGenerator<Creature> >::Update (this=0x7fff83cd7680, owner=0x7fff83164000, diff=100)
    at /home/gameadm/source/trinity/src/server/game/Movement/MovementGenerator.h:102
#18 0x0000555556bb46b9 in MotionMaster::Update (this=0x7fff83a0ae80, diff=100) at /home/gameadm/source/trinity/src/server/game/Movement/MotionMaster.cpp:316
#19 0x00005555567b132e in Unit::Update (this=0x7fff83164000, p_time=100) at /home/gameadm/source/trinity/src/server/game/Entities/Unit/Unit.cpp:465
#20 0x00005555565b1405 in Creature::Update (this=0x7fff83164000, diff=100) at /home/gameadm/source/trinity/src/server/game/Entities/Creature/Creature.cpp:802
#21 0x00005555569dd8ad in Trinity::ObjectUpdater::Visit<Creature> (this=0x7fff999fd2ac, m=...) at /home/gameadm/source/trinity/src/server/game/Grids/Notifiers/GridNotifiers.cpp:405
#22 0x0000555556b86d4d in VisitorHelper<Trinity::ObjectUpdater, Creature> (v=..., c=...) at /home/gameadm/source/trinity/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:44
#23 0x0000555556b85a9f in VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > (v=..., c=...)
    at /home/gameadm/source/trinity/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:50
#24 0x0000555556b83b7e in VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > (v=..., c=...)
    at /home/gameadm/source/trinity/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:51
#25 0x0000555556b7e760 in VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (v=..., c=...)
    at /home/gameadm/source/trinity/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:57
#26 0x0000555556b7a0b2 in TypeContainerVisitor<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >::Visit (
    this=0x7fff999fd2b0, c=...) at /home/gameadm/source/trinity/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:91
#27 0x0000555556b7265f in Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::Visit<Trinity::ObjectUpdater> (this=0x7fffc55200d8, visitor=...) at /home/gameadm/source/trinity/src/server/game/Grids/Grid.h:90
#28 0x0000555556b65b7c in NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (this=0x7fffc551af40, x=6, y=4, visitor=...)
    at /home/gameadm/source/trinity/src/server/game/Grids/NGrid.h:151
#29 0x0000555556b5a8b2 in Map::Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > > (this=0x7fffc2d71400, 
    cell=..., visitor=...) at /home/gameadm/source/trinity/src/server/game/Maps/Map.h:986
#30 0x0000555556b37c9c in Map::VisitNearbyCellsOf (this=0x7fffc2d71400, obj=0x7fffc4e3fb40, gridVisitor=..., worldVisitor=...) at /home/gameadm/source/trinity/src/server/game/Maps/Map.cpp:743
#31 0x0000555556b38159 in Map::Update (this=0x7fffc2d71400, t_diff=100) at /home/gameadm/source/trinity/src/server/game/Maps/Map.cpp:810
#32 0x0000555556ba2019 in MapUpdateRequest::call (this=0x7fffc583cbc0) at /home/gameadm/source/trinity/src/server/game/Maps/MapUpdater.cpp:44
#33 0x0000555556ba1cb9 in MapUpdater::WorkerThread (this=0x555558594440 <MapManager::instance()::instance+160>) at /home/gameadm/source/trinity/src/server/game/Maps/MapUpdater.cpp:119
--Type <RET> for more, q to quit, c to continue without paging--

#34 0x0000555556ba38c0 in std::__invoke_impl<void, void (MapUpdater::*)(), MapUpdater*> (__f=@0x7fffbc4e30d0: (void (MapUpdater::*)(MapUpdater * const)) 0x555556ba1c2a <MapUpdater::WorkerThread()>, 
    __t=@0x7fffbc4e30c8: 0x555558594440 <MapManager::instance()::instance+160>) at /usr/include/c++/9/bits/invoke.h:73
#35 0x0000555556ba37ee in std::__invoke<void (MapUpdater::*)(), MapUpdater*> (__fn=@0x7fffbc4e30d0: (void (MapUpdater::*)(MapUpdater * const)) 0x555556ba1c2a <MapUpdater::WorkerThread()>)
    at /usr/include/c++/9/bits/invoke.h:95
#36 0x0000555556ba374d in std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> >::_M_invoke<0ul, 1ul> (this=0x7fffbc4e30c8) at /usr/include/c++/9/thread:244
#37 0x0000555556ba3704 in std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> >::operator() (this=0x7fffbc4e30c8) at /usr/include/c++/9/thread:251
#38 0x0000555556ba36e4 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> > >::_M_run (this=0x7fffbc4e30c0) at /usr/include/c++/9/thread:195
#39 0x00007ffff72a3d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#40 0x00007ffff73d9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#41 0x00007ffff6f91293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)```

**Comment by Mr-Deadbeat** [comment]
forgot to mention i've done that same escort quest previously on the previous commit of trinity-bots so something has changed between revisions

**Comment by trickerer** [comment]
It's conditions it seems
