### ISSUE TITLE
[TC] [Crash] bot_necromancer_ai.cpp crash

### ISSUE THREAD

**Issue by zzyyll2** [trickerer/Trinity-Bots#450]
```
commit 722795c7930dccf3c486fbd2ef6be09fe1121eb6 (origin/npcbots_3.3.5, origin/HEAD, npcbots_3.3.5)
Author: trickerer <onlysuffering@gmail.com>
Date:   Thu May 4 12:08:47 2023 +0700
```

crash detail is:
```
(gdb) bt
#0  0x00005561ec3f24a7 in Object::GetUInt32Value (this=0x7f074596a000, index=67) at /TrinityCore/src/server/game/Entities/Object/Object.cpp:278
#1  0x00005561ecaa7f4b in Unit::GetDisplayId (this=0x7f074596a000) at /TrinityCore/src/server/game/Entities/Unit/Unit.h:1589
#2  necromancer_bot::necromancer_botAI::UpdateAI (this=0x7f075feda000, diff=26) at /TrinityCore/src/server/game/AI/NpcBots/bot_necromancer_ai.cpp:326
#3  0x00005561ec51e51d in Unit::AIUpdateTick (this=0x7f07600bf000, diff=67) at /TrinityCore/src/server/game/Entities/Unit/Unit.cpp:9861
#4  0x00005561ec3ae3f4 in Creature::Update (this=0x7f07600bf000, diff=26) at /TrinityCore/src/server/game/Entities/Creature/Creature.cpp:868
#5  0x00005561ec63d656 in Trinity::ObjectUpdater::Visit<Creature> (this=0x7f07825fd4a0, m=...) at /TrinityCore/src/server/game/Grids/Notifiers/GridNotifiers.cpp:429
#6  0x00005561ec744110 in VisitorHelper<Trinity::ObjectUpdater, Creature> (v=..., c=...) at /TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:44
#7  VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > (v=..., c=...)
    at /TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:50
#8  VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > (v=..., c=...)
    at /TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:51
#9  VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (v=..., c=...)
    at /TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:57
#10 TypeContainerVisitor<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >::Visit (
    this=<optimized out>, c=...) at /TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:91
#11 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::Visit<Trinity::ObjectUpdater> (this=<optimized out>, visitor=...) at /TrinityCore/src/server/game/Grids/Grid.h:90
#12 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (
    this=<optimized out>, x=<optimized out>, y=<optimized out>, visitor=...) at /TrinityCore/src/server/game/Grids/NGrid.h:151
#13 0x00005561ec7276b4 in Map::Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > > (
    this=0x7f078a845780, cell=..., visitor=...) at /TrinityCore/src/server/game/Maps/Map.h:990
#14 Map::VisitNearbyCellsOf (this=this@entry=0x7f078a845780, obj=obj@entry=0x7f0744cef000, gridVisitor=..., worldVisitor=...) at /TrinityCore/src/server/game/Maps/Map.cpp:744
#15 0x00005561ec728164 in Map::Update (this=0x7f078a845780, t_diff=<optimized out>) at /TrinityCore/src/server/game/Maps/Map.cpp:865
#16 0x00005561ec75ba35 in MapUpdateRequest::call (this=0x7f078a46fc40) at /TrinityCore/src/server/game/Maps/MapUpdater.cpp:43
#17 0x00005561ec75b5d7 in MapUpdater::WorkerThread (this=0x5561ed495080 <MapManager::instance()::instance+160>) at /TrinityCore/src/server/game/Maps/MapUpdater.cpp:118
#18 0x00007f07c897e2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007f07c8607b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#20 0x00007f07c8699a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

```
![image](https://user-images.githubusercontent.com/22398806/236617158-98b9dd65-908f-4aa7-b7e6-2a87f4296d8e.png)

some debug info:
![image](https://user-images.githubusercontent.com/22398806/236617246-351a29c0-3eff-42b0-889d-5b1a404ebc5d.png)

i found m_uint32Values = 0x0;

```
uint32 Object::GetUInt32Value(uint16 index) const
{
    ASSERT(index < m_valuesCount || PrintIndexError(index, false));
    return m_uint32Values[index];
}
```

thanks.

**Comment by trickerer** [comment]
Fixed in https://github.com/trickerer/Trinity-Bots/commit/19cf3eee233720ef0a02904f5bb436e35f22b4c2
